spring:
  application.name: GraphQL
  datasource:
    initialize: false

logging.level:
  org.springframework: info

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
    mapping: /graphiql

max-query-depth: 10